### PR TITLE
Rename `django-idom` to `reactpy-django`

### PR DESCRIPTION
**Pull request by Archmonger**
## Description

Performs any changes needed to rename from `idom` to `reactpy`.

## Checklist:

Please update this checklist as you complete each item:

-   [x] Tests have been included for all bug fixes or added functionality.
-   [ ] The changelog has been updated with any significant changes, if necessary.
-   [x] GitHub Issues which may be closed by this PR have been linked.

### CODE REVIEW

**Comment by Archmonger** [comment]
Couple of things are needed for these tests to pass

1) `reactpy` 1.0.0 release for parity to `idom`
   - Why did we revert versions when renaming the package...?
2) `reactpy-router` stub repo
3) `django-reactpy` stub repo

**Comment by rmorshea** [comment]
I guess I figured that if we wanted to release a 1.0 version of ReactPy we'd need to remove the existing tag. Releasing a 0.45.0 version was mostly a result of me rushing to get a release out after I cleared out the previous releases.

**Comment by rmorshea** [comment]
Let's go with beginning all names with `reactpy-` for consistency. Also, why do we need stub repos? Can't we just rehome this repo?

**Comment by rmorshea** [comment]
Ok I see. I think we can merge despite the docs build failing. We'll just rehome the repo and then rerun the tests.

**Comment by Archmonger** [comment]
Can we re-release ReactPy as 1.0.0?

**Comment by rmorshea** [comment]
[`@reactpy/client`](https://www.npmjs.com/package/@reactpy/client) has been released. You should be able to use this without any changes. The next release of the client (assuming there's nothing wrong with v0.1.0) will be the typescript rewrite.

**Comment by Archmonger** [comment]
The version number regressions of the JS and Python packages are really unnatural.

**Comment by rmorshea** [comment]
The zero version on the Python package is temporary. I'm working on publishing a 1.0 release momentarily.

**Comment by rmorshea** [comment]
v1.0 of reactpy Python lib had been released.

**Comment by rmorshea** [comment]
@Archmonger, because GitHub aggressively strips all style from inline HTML there is no way to copy-paste a common markdown header to all our repos with a simple "ReactPy" to "ReactPy <Whatever>" title change. From what I can tell, each repo will need its own landscape logo file with the modified title.

**Comment by rmorshea** [comment]
The only alternative I can think of would be to do something like:

```
# <img src="https://raw.githubusercontent.com/reactive-python/reactpy/main/branding/svg/reactpy-logo-square.svg" alt="ReactPy Logo" style="height: 2rem; vertical-align: text-bottom" /> ReactPy
```

image

Since for some reason `img` elements seem to allow inline style. The current logo doesn't really work well at this scale, but perhaps the best option for right now.

**Comment by Archmonger** [comment]
By landscape, do you mean center justified?

**Comment by rmorshea** [comment]
By landscape I mean [this style of logo](https://github.com/reactive-python/reactpy/blob/reusable-readme-title/branding/svg/reactpy-logo-landscape.svg).

**Comment by Archmonger** [comment]
I've done something similar using the `align` image property in the past.

```md
# ReactPy <img src="https://raw.githubusercontent.com/reactive-python/reactpy/main/branding/svg/reactpy-logo-square.svg" align="left" height="40"/>
```

# ReactPy

**Comment by rmorshea** [comment]
Let's go with the logo setup you have there. After that I think this LGTM.

**Comment by Archmonger** [comment]
The tagline didn't really have a good place with the new logo design, so I opted to remove it. I think we should just keep that text in the github sidebar moving forward.

Take a look at the design here: https://github.com/Archmonger/django-idom/tree/django-reactpy

**Comment by rmorshea** [comment]
do you think we need the backends table here?

**Comment by Archmonger** [comment]
Not from a technical standpoint, but it's free advertising that doesn't feel like advertising.

The more click-throughs we get, the more we can snowball our overall popularity.

**Comment by rmorshea** [comment]
I was planning to rehome the repo right after merging so perhaps we could leave the urls as is.

**Comment by Archmonger** [comment]
It's very little extra effort to do a follow up PR to change URLs.

We're already seeing some instances of confusion on the IDOM core docs.

**Review by rmorshea — APPROVED** [review]
I'm good with things as they are so approving. feel free to make those url changes though.

**Comment by rmorshea** [comment]
Good to merge?

**Comment by Archmonger** [comment]
That last commit revealed some holes in my link checking workflow.

Since the `README` and `CHANGELOG` aren't in the docs directory they aren't getting checked.

Also one more thing I want to revert is maintaining the `idom` name in the legacy changelog versions.

**Comment by rmorshea** [comment]
Ok, just at me when it's ready and I'll merge/rehome.

**Comment by Archmonger** [comment]
Since I didn't revert any `reactpy-django` references in the docs, I think we should repo transfer before merging this PR to prevent broken docs links.

Also, our logo solution doesn't play well with `mkdocs` so I might have to do some changes to make that work.

**Comment by rmorshea** [comment]
LGTM!

**Pull request merged**
