### PR TITLE
Fix grammar in readme

### PR DESCRIPTION
**Pull request by Archmonger**
## Description

Change `similarly` to `similar` to be gramatically correct.

## Checklist:

Please update this checklist as you complete each item:

-   [x] Tests have been included for all bug fixes or added functionality.
-   [x] The changelog has been updated with any significant changes, if necessary.
-   [x] GitHub Issues which may be closed by this PR have been linked.

### CODE REVIEW

**Comment by rmorshea** [comment]
According to ChatGPT "similarly" is the correct word to use:

> Prompt: In the sentence “ReactPy is a library for building user interfaces in Python without Javascript. ReactPy interfaces are made from components which look and behave similarly to those found in ReactJS.” is it more grammatically correct to use “similar” or “similarly”?
> Response: In the given sentence, "similarly" is the correct word to use as it is an adverb that modifies the verb "behave," indicating how the components behave. Using "similar" would be grammatically incorrect because it is an adjective that describes a noun, not a verb. Therefore, "similarly" is the correct choice to convey the intended meaning of the sentence.

**Comment by Archmonger** [comment]
Hmmm... I'll double check some grammar rules.

To show a different scenario, `similarly` feels weird though:

`The dog looks similar to my cat`
`The dog looks similarly to my cat`

... and then with behaves:

`The dog behaves similar to my cat`
`The dog behaves similarly to my cat`

**Comment by Archmonger** [comment]
Looks like `grammarly` thinks both of them are correct.

It did catch a different grammar issue `which look` -> `that look`

**Comment by Archmonger** [comment]
I used ChatGPT to help brainstorm ways we can wordsmith this better. I took a couple sentences from 3 different ChatGPT prompts and this is what I got:

Looking to build web interfaces in Python without the hassle of JavaScript? [ReactPy](https://reactpy.dev/) is designed to give you the look and feel of [ReactJS](https://reactjs.org/) without the JavaScript clutter. Whether you're a seasoned web developer or just starting out, ReactPy is easy to use and can grow with your ambitions. Check out the example below to see how ReactPy can simplify your Python web development workflow.

**Review by rmorshea — APPROVED** [review]

**Comment by Archmonger** [comment]
@rmorshea Do we want to consider the ChatGPT version above?

**Comment by Archmonger** [comment]
Merging this PR, we can talk about the ChatGPT readme separately.

**Pull request merged**
